subtitle = "Sebuah Blog tentang teknologi, pemrograman, dan hal berkaitan semacam itu"
menuMore = "Tampilkan lebih banyak"
readMore = "Baca selengkapnya"
readOtherPosts = "Baca postingan lain"
newerPosts = "Postingan lebih baru"
olderPosts = "Postingan lebih lama"
missingContentMessage = "Halaman tidak ditemukan..."
missingBackButtonLabel = "Kembali ke beranda"
minuteReadingTime = "menit baca"
words = "kata"
updateDatePrefix = "Updated"
